spring.application.name=orders

spring.datasource.url=jdbc:postgresql://localhost:5443/pg-order
spring.datasource.username=pg-order
spring.datasource.password=0706

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true